apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: full-sample-
spec:
  entrypoint: template-steps
  arguments:
    parameters:
      - name: intput_param
        value: "Echuca"  # default value
  templates:
  - name: template-steps
    
    